export const VIEWS = {
    DASHBOARD: 'DASHBOARD',
    DETECTION: 'DETECTION',
    LEARN: 'LEARN',
    PROGRESS: 'PROGRESS',
    SETTINGS: 'SETTINGS',
    MEMBERS: 'MEMBERS',
    ADD_USER: 'ADD_USER',
    ISSUES: 'ISSUES',
    ANALYTICS: 'ANALYTICS',
};